name: API Base Push Test

on:
  push:
    branches: [master, db-pgsql]
  pull_request:
    branches: [master, db-pgsql]

jobs:
  lumen-api-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: db_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: |
          composer install -n --prefer-dist --no-interaction --no-suggest
          composer dump-autoload

      - name: Prepare Laravel application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan cache:clear

      - name: Run Migrations
        run: |
          php artisan migrate:fresh
        env:
          PORT: ${{ job.services.postgres.ports[3306] }}

      - name: Execute tests (Unit and Feature tests) via PHPUnit (PEST)
        run: ./vendor/bin/pest
        env:
          PORT: ${{ job.services.postgres.ports[3306] }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
