name: API Base Push Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lumen-api-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Run composer install
        run: |
          composer install -n --prefer-dist --no-interaction --no-suggest
          composer dump-autoload

      - name: Prepare Laravel application
        run: |
          cp .env.ci .env
          php artisan key:generate
          php artisan cache:clear

      - name: Run Migrations
        run: |
          php artisan migrate:fresh
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Execute tests (Unit and Feature tests) via PHPUnit (PEST)
        run: ./vendor/bin/pest
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
